# Generated by Django 4.0.5 on 2022-09-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserProfile', '0002_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='addressline1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='addressline2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
