# Generated by Django 4.0.5 on 2022-09-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserProfile', '0003_remove_userprofile_addressline1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
