# Generated by Django 4.0.5 on 2022-09-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserProfile', '0005_remove_userprofile_address_userprofile_addressline1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='addressline1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
