# Generated by Django 4.0.5 on 2022-09-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserProfile', '0009_userprofile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(max_length=25),
        ),
    ]
